
/*
 *************************************************************************
 * The contents of this file are subject to the Openbravo  Public  License
 * Version  1.1  (the  "License"),  being   the  Mozilla   Public  License
 * Version 1.1  with a permitted attribution clause; you may not  use this
 * file except in compliance with the License. You  may  obtain  a copy of
 * the License at http://www.openbravo.com/legal/license.html
 * Software distributed under the License  is  distributed  on  an "AS IS"
 * basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
 * License for the specific  language  governing  rights  and  limitations
 * under the License.
 * The Original Code is Openbravo ERP.
 * The Initial Developer of the Original Code is Openbravo SLU
 * All portions are Copyright (C) 2008-2020 Openbravo SLU
 * All Rights Reserved.
 * Contributor(s):  ______________________________________.
 ************************************************************************
*/
package org.openbravo.model.manufacturing.maintenance;

import java.math.BigDecimal;
import java.util.Date;

import org.openbravo.base.structure.ActiveEnabled;
import org.openbravo.base.structure.BaseOBObject;
import org.openbravo.base.structure.ClientEnabled;
import org.openbravo.base.structure.OrganizationEnabled;
import org.openbravo.base.structure.Traceable;
import org.openbravo.model.ad.access.User;
import org.openbravo.model.ad.system.Client;
import org.openbravo.model.common.enterprise.Organization;
import org.openbravo.model.manufacturing.floorshop.Machine;
import org.openbravo.model.manufacturing.floorshop.MachineType;
import org.openbravo.model.materialmgmt.transaction.InternalConsumption;
/**
 * Entity class for entity ManufacturingMaintenanceSchedule (stored in table MA_Maint_Scheduled).
 * <br>
 * Help: {@literal Scheduled maintenances. Here there are all the maintenances done in the application, those
     *       generated by the maintenance periodicity or manually inserted.}
 * <br>
 * NOTE: This class should not be instantiated directly. To instantiate this
 * class the {@link org.openbravo.base.provider.OBProvider} should be used.
 */
public class MaintenanceSchedule extends BaseOBObject implements Traceable, ClientEnabled, OrganizationEnabled, ActiveEnabled {
    private static final long serialVersionUID = 1L;
    public static final String TABLE_NAME = "MA_Maint_Scheduled";
    public static final String ENTITY_NAME = "ManufacturingMaintenanceSchedule";

    /**
     * Property id stored in column MA_Maint_Scheduled_ID in table MA_Maint_Scheduled 
     * 
     */
    public static final String PROPERTY_ID = "id";

    /**
     * Property client stored in column AD_Client_ID in table MA_Maint_Scheduled 
     * @see ClientEnabled 
     * 
     */
    public static final String PROPERTY_CLIENT = "client";

    /**
     * Property organization stored in column AD_Org_ID in table MA_Maint_Scheduled 
     * @see OrganizationEnabled 
     * 
     */
    public static final String PROPERTY_ORGANIZATION = "organization";

    /**
     * Property active stored in column IsActive in table MA_Maint_Scheduled 
     * @see ActiveEnabled 
     * 
     */
    public static final String PROPERTY_ACTIVE = "active";

    /**
     * Property creationDate stored in column Created in table MA_Maint_Scheduled 
     * @see Traceable 
     * 
     */
    public static final String PROPERTY_CREATIONDATE = "creationDate";

    /**
     * Property createdBy stored in column Createdby in table MA_Maint_Scheduled 
     * @see Traceable 
     * 
     */
    public static final String PROPERTY_CREATEDBY = "createdBy";

    /**
     * Property updated stored in column Updated in table MA_Maint_Scheduled 
     * @see Traceable 
     * 
     */
    public static final String PROPERTY_UPDATED = "updated";

    /**
     * Property updatedBy stored in column Updatedby in table MA_Maint_Scheduled 
     * @see Traceable 
     * 
     */
    public static final String PROPERTY_UPDATEDBY = "updatedBy";

    /**
     * Property maintenance stored in column MA_Maintenance_ID in table MA_Maint_Scheduled<br>
     * Help: {@literal Identifies a maintenance of a machine or machine category.}
     * 
     */
    public static final String PROPERTY_MAINTENANCE = "maintenance";

    /**
     * Property maintenanceOrder stored in column MA_Maint_Part_ID in table MA_Maint_Scheduled<br>
     * Help: {@literal Identifies a maintenance part.}
     * 
     */
    public static final String PROPERTY_MAINTENANCEORDER = "maintenanceOrder";

    /**
     * Property machine stored in column MA_Machine_ID in table MA_Maint_Scheduled<br>
     * Help: {@literal Indicates a machine of the enterprise.}
     * 
     */
    public static final String PROPERTY_MACHINE = "machine";

    /**
     * Property machineCategory stored in column MA_Machine_Type_ID in table MA_Maint_Scheduled<br>
     * Help: {@literal Identifies a machine category.}
     * 
     */
    public static final String PROPERTY_MACHINECATEGORY = "machineCategory";

    /**
     * Property maintenanceType stored in column Maintenance_Type in table MA_Maint_Scheduled<br>
     * Help: {@literal Sets the maintenance type, available options are corrective, corrective (urgent) and
     *       preventive.}
     * 
     */
    public static final String PROPERTY_MAINTENANCETYPE = "maintenanceType";

    /**
     * Property plannedDate stored in column Scheduleddate in table MA_Maint_Scheduled 
     * 
     */
    public static final String PROPERTY_PLANNEDDATE = "plannedDate";

    /**
     * Property confirmation stored in column Confirmed in table MA_Maint_Scheduled<br>
     * Help: {@literal Indicates that the maintenance schedule has been confirmed.}
     * 
     */
    public static final String PROPERTY_CONFIRMATION = "confirmation";

    /**
     * Property shift stored in column Shift in table MA_Maint_Scheduled<br>
     * Help: {@literal Indicates the shift when the group is going to be measured. Available options are morning
     *       and swing shift}
     * 
     */
    public static final String PROPERTY_SHIFT = "shift";

    /**
     * Property result stored in column Result in table MA_Maint_Scheduled<br>
     * Help: {@literal The Result indicates the result of any action taken on this request.}
     * 
     */
    public static final String PROPERTY_RESULT = "result";

    /**
     * Property comments stored in column Observation in table MA_Maint_Scheduled<br>
     * Help: {@literal Observations occurred during the process or operation.}
     * 
     */
    public static final String PROPERTY_COMMENTS = "comments";

    /**
     * Property timeUsed stored in column Usedtime in table MA_Maint_Scheduled<br>
     * Help: {@literal Used time in hours.}
     * 
     */
    public static final String PROPERTY_TIMEUSED = "timeUsed";

    /**
     * Property description stored in column Description in table MA_Maint_Scheduled<br>
     * Help: {@literal A description is limited to 255 characters.}
     * 
     */
    public static final String PROPERTY_DESCRIPTION = "description";

    /**
     * Property maintenanceTask stored in column MA_Maint_Operation_ID in table MA_Maint_Scheduled<br>
     * Help: {@literal Identifies a maintenance operation.}
     * 
     */
    public static final String PROPERTY_MAINTENANCETASK = "maintenanceTask";

    /**
     * Property internalConsumption stored in column M_Internal_Consumption_ID in table MA_Maint_Scheduled<br>
     * Help: {@literal Identifies an internal consumption of products.}
     * 
     */
    public static final String PROPERTY_INTERNALCONSUMPTION = "internalConsumption";


    public MaintenanceSchedule() {
        setDefaultValue(PROPERTY_ACTIVE, true);
        setDefaultValue(PROPERTY_CONFIRMATION, false);
        setDefaultValue(PROPERTY_RESULT, false);
    }

    @Override
    public String getEntityName() {
        return ENTITY_NAME;
    }

    /**
     * @see MaintenanceSchedule#PROPERTY_ID
     * 
     */
    public String getId() {
        return (String) get(PROPERTY_ID);
    }
    /**
     * @see MaintenanceSchedule#PROPERTY_ID
     * 
     */
    public void setId(String id) {
        set(PROPERTY_ID, id);
    }

    /**
     * @see MaintenanceSchedule#PROPERTY_CLIENT
     * 
     */
    public Client getClient() {
        return (Client) get(PROPERTY_CLIENT);
    }
    /**
     * @see MaintenanceSchedule#PROPERTY_CLIENT
     * 
     */
    public void setClient(Client client) {
        set(PROPERTY_CLIENT, client);
    }

    /**
     * @see MaintenanceSchedule#PROPERTY_ORGANIZATION
     * 
     */
    public Organization getOrganization() {
        return (Organization) get(PROPERTY_ORGANIZATION);
    }
    /**
     * @see MaintenanceSchedule#PROPERTY_ORGANIZATION
     * 
     */
    public void setOrganization(Organization organization) {
        set(PROPERTY_ORGANIZATION, organization);
    }

    /**
     * @see MaintenanceSchedule#PROPERTY_ACTIVE
     * 
     */
    public Boolean isActive() {
        return (Boolean) get(PROPERTY_ACTIVE);
    }
    /**
     * @see MaintenanceSchedule#PROPERTY_ACTIVE
     * 
     */
    public void setActive(Boolean active) {
        set(PROPERTY_ACTIVE, active);
    }

    /**
     * @see MaintenanceSchedule#PROPERTY_CREATIONDATE
     * 
     */
    public Date getCreationDate() {
        return (Date) get(PROPERTY_CREATIONDATE);
    }
    /**
     * @see MaintenanceSchedule#PROPERTY_CREATIONDATE
     * 
     */
    public void setCreationDate(Date creationDate) {
        set(PROPERTY_CREATIONDATE, creationDate);
    }

    /**
     * @see MaintenanceSchedule#PROPERTY_CREATEDBY
     * 
     */
    public User getCreatedBy() {
        return (User) get(PROPERTY_CREATEDBY);
    }
    /**
     * @see MaintenanceSchedule#PROPERTY_CREATEDBY
     * 
     */
    public void setCreatedBy(User createdBy) {
        set(PROPERTY_CREATEDBY, createdBy);
    }

    /**
     * @see MaintenanceSchedule#PROPERTY_UPDATED
     * 
     */
    public Date getUpdated() {
        return (Date) get(PROPERTY_UPDATED);
    }
    /**
     * @see MaintenanceSchedule#PROPERTY_UPDATED
     * 
     */
    public void setUpdated(Date updated) {
        set(PROPERTY_UPDATED, updated);
    }

    /**
     * @see MaintenanceSchedule#PROPERTY_UPDATEDBY
     * 
     */
    public User getUpdatedBy() {
        return (User) get(PROPERTY_UPDATEDBY);
    }
    /**
     * @see MaintenanceSchedule#PROPERTY_UPDATEDBY
     * 
     */
    public void setUpdatedBy(User updatedBy) {
        set(PROPERTY_UPDATEDBY, updatedBy);
    }

    /**
     * @see MaintenanceSchedule#PROPERTY_MAINTENANCE
     * 
     */
    public Maintenance getMaintenance() {
        return (Maintenance) get(PROPERTY_MAINTENANCE);
    }
    /**
     * @see MaintenanceSchedule#PROPERTY_MAINTENANCE
     * 
     */
    public void setMaintenance(Maintenance maintenance) {
        set(PROPERTY_MAINTENANCE, maintenance);
    }

    /**
     * @see MaintenanceSchedule#PROPERTY_MAINTENANCEORDER
     * 
     */
    public MainteanceOrder getMaintenanceOrder() {
        return (MainteanceOrder) get(PROPERTY_MAINTENANCEORDER);
    }
    /**
     * @see MaintenanceSchedule#PROPERTY_MAINTENANCEORDER
     * 
     */
    public void setMaintenanceOrder(MainteanceOrder maintenanceOrder) {
        set(PROPERTY_MAINTENANCEORDER, maintenanceOrder);
    }

    /**
     * @see MaintenanceSchedule#PROPERTY_MACHINE
     * 
     */
    public Machine getMachine() {
        return (Machine) get(PROPERTY_MACHINE);
    }
    /**
     * @see MaintenanceSchedule#PROPERTY_MACHINE
     * 
     */
    public void setMachine(Machine machine) {
        set(PROPERTY_MACHINE, machine);
    }

    /**
     * @see MaintenanceSchedule#PROPERTY_MACHINECATEGORY
     * 
     */
    public MachineType getMachineCategory() {
        return (MachineType) get(PROPERTY_MACHINECATEGORY);
    }
    /**
     * @see MaintenanceSchedule#PROPERTY_MACHINECATEGORY
     * 
     */
    public void setMachineCategory(MachineType machineCategory) {
        set(PROPERTY_MACHINECATEGORY, machineCategory);
    }

    /**
     * @see MaintenanceSchedule#PROPERTY_MAINTENANCETYPE
     * 
     */
    public String getMaintenanceType() {
        return (String) get(PROPERTY_MAINTENANCETYPE);
    }
    /**
     * @see MaintenanceSchedule#PROPERTY_MAINTENANCETYPE
     * 
     */
    public void setMaintenanceType(String maintenanceType) {
        set(PROPERTY_MAINTENANCETYPE, maintenanceType);
    }

    /**
     * @see MaintenanceSchedule#PROPERTY_PLANNEDDATE
     * 
     */
    public Date getPlannedDate() {
        return (Date) get(PROPERTY_PLANNEDDATE);
    }
    /**
     * @see MaintenanceSchedule#PROPERTY_PLANNEDDATE
     * 
     */
    public void setPlannedDate(Date plannedDate) {
        set(PROPERTY_PLANNEDDATE, plannedDate);
    }

    /**
     * @see MaintenanceSchedule#PROPERTY_CONFIRMATION
     * 
     */
    public Boolean isConfirmation() {
        return (Boolean) get(PROPERTY_CONFIRMATION);
    }
    /**
     * @see MaintenanceSchedule#PROPERTY_CONFIRMATION
     * 
     */
    public void setConfirmation(Boolean confirmation) {
        set(PROPERTY_CONFIRMATION, confirmation);
    }

    /**
     * @see MaintenanceSchedule#PROPERTY_SHIFT
     * 
     */
    public String getShift() {
        return (String) get(PROPERTY_SHIFT);
    }
    /**
     * @see MaintenanceSchedule#PROPERTY_SHIFT
     * 
     */
    public void setShift(String shift) {
        set(PROPERTY_SHIFT, shift);
    }

    /**
     * @see MaintenanceSchedule#PROPERTY_RESULT
     * 
     */
    public Boolean isResult() {
        return (Boolean) get(PROPERTY_RESULT);
    }
    /**
     * @see MaintenanceSchedule#PROPERTY_RESULT
     * 
     */
    public void setResult(Boolean result) {
        set(PROPERTY_RESULT, result);
    }

    /**
     * @see MaintenanceSchedule#PROPERTY_COMMENTS
     * 
     */
    public String getComments() {
        return (String) get(PROPERTY_COMMENTS);
    }
    /**
     * @see MaintenanceSchedule#PROPERTY_COMMENTS
     * 
     */
    public void setComments(String comments) {
        set(PROPERTY_COMMENTS, comments);
    }

    /**
     * @see MaintenanceSchedule#PROPERTY_TIMEUSED
     * 
     */
    public BigDecimal getTimeUsed() {
        return (BigDecimal) get(PROPERTY_TIMEUSED);
    }
    /**
     * @see MaintenanceSchedule#PROPERTY_TIMEUSED
     * 
     */
    public void setTimeUsed(BigDecimal timeUsed) {
        set(PROPERTY_TIMEUSED, timeUsed);
    }

    /**
     * @see MaintenanceSchedule#PROPERTY_DESCRIPTION
     * 
     */
    public String getDescription() {
        return (String) get(PROPERTY_DESCRIPTION);
    }
    /**
     * @see MaintenanceSchedule#PROPERTY_DESCRIPTION
     * 
     */
    public void setDescription(String description) {
        set(PROPERTY_DESCRIPTION, description);
    }

    /**
     * @see MaintenanceSchedule#PROPERTY_MAINTENANCETASK
     * 
     */
    public Task getMaintenanceTask() {
        return (Task) get(PROPERTY_MAINTENANCETASK);
    }
    /**
     * @see MaintenanceSchedule#PROPERTY_MAINTENANCETASK
     * 
     */
    public void setMaintenanceTask(Task maintenanceTask) {
        set(PROPERTY_MAINTENANCETASK, maintenanceTask);
    }

    /**
     * @see MaintenanceSchedule#PROPERTY_INTERNALCONSUMPTION
     * 
     */
    public InternalConsumption getInternalConsumption() {
        return (InternalConsumption) get(PROPERTY_INTERNALCONSUMPTION);
    }
    /**
     * @see MaintenanceSchedule#PROPERTY_INTERNALCONSUMPTION
     * 
     */
    public void setInternalConsumption(InternalConsumption internalConsumption) {
        set(PROPERTY_INTERNALCONSUMPTION, internalConsumption);
    }

}
