
/*
 *************************************************************************
 * The contents of this file are subject to the Openbravo  Public  License
 * Version  1.1  (the  "License"),  being   the  Mozilla   Public  License
 * Version 1.1  with a permitted attribution clause; you may not  use this
 * file except in compliance with the License. You  may  obtain  a copy of
 * the License at http://www.openbravo.com/legal/license.html
 * Software distributed under the License  is  distributed  on  an "AS IS"
 * basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
 * License for the specific  language  governing  rights  and  limitations
 * under the License.
 * The Original Code is Openbravo ERP.
 * The Initial Developer of the Original Code is Openbravo SLU
 * All portions are Copyright (C) 2008-2020 Openbravo SLU
 * All Rights Reserved.
 * Contributor(s):  ______________________________________.
 ************************************************************************
*/
package org.openbravo.model.financialmgmt.tax;

import java.math.BigDecimal;
import java.util.Date;

import org.openbravo.base.structure.ActiveEnabled;
import org.openbravo.base.structure.BaseOBObject;
import org.openbravo.base.structure.ClientEnabled;
import org.openbravo.base.structure.OrganizationEnabled;
import org.openbravo.base.structure.Traceable;
import org.openbravo.model.ad.access.User;
import org.openbravo.model.ad.system.Client;
import org.openbravo.model.common.enterprise.Organization;
import org.openbravo.model.common.invoice.InvoiceTax;
/**
 * Entity class for entity FinancialMgmtTaxRegisterline (stored in table C_TaxRegisterline).
 * <br>
 * Help: {@literal Lines of Tax Register}
 * <br>
 * NOTE: This class should not be instantiated directly. To instantiate this
 * class the {@link org.openbravo.base.provider.OBProvider} should be used.
 */
public class TaxRegisterline extends BaseOBObject implements Traceable, ClientEnabled, OrganizationEnabled, ActiveEnabled {
    private static final long serialVersionUID = 1L;
    public static final String TABLE_NAME = "C_TaxRegisterline";
    public static final String ENTITY_NAME = "FinancialMgmtTaxRegisterline";

    /**
     * Property client stored in column AD_Client_ID in table C_TaxRegisterline 
     * @see ClientEnabled 
     * 
     */
    public static final String PROPERTY_CLIENT = "client";

    /**
     * Property organization stored in column AD_Org_ID in table C_TaxRegisterline 
     * @see OrganizationEnabled 
     * 
     */
    public static final String PROPERTY_ORGANIZATION = "organization";

    /**
     * Property active stored in column IsActive in table C_TaxRegisterline 
     * @see ActiveEnabled 
     * 
     */
    public static final String PROPERTY_ACTIVE = "active";

    /**
     * Property creationDate stored in column Created in table C_TaxRegisterline 
     * @see Traceable 
     * 
     */
    public static final String PROPERTY_CREATIONDATE = "creationDate";

    /**
     * Property createdBy stored in column Createdby in table C_TaxRegisterline 
     * @see Traceable 
     * 
     */
    public static final String PROPERTY_CREATEDBY = "createdBy";

    /**
     * Property updated stored in column Updated in table C_TaxRegisterline 
     * @see Traceable 
     * 
     */
    public static final String PROPERTY_UPDATED = "updated";

    /**
     * Property updatedBy stored in column Updatedby in table C_TaxRegisterline 
     * @see Traceable 
     * 
     */
    public static final String PROPERTY_UPDATEDBY = "updatedBy";

    /**
     * Property id stored in column C_Taxregisterline_ID in table C_TaxRegisterline 
     * 
     */
    public static final String PROPERTY_ID = "id";

    /**
     * Property taxRegister stored in column C_Taxregister_ID in table C_TaxRegisterline<br>
     * Help: {@literal Tax register}
     * 
     */
    public static final String PROPERTY_TAXREGISTER = "taxRegister";

    /**
     * Property invoiceTax stored in column C_Invoicetax_ID in table C_TaxRegisterline<br>
     * Help: {@literal Invoice Tax}
     * 
     */
    public static final String PROPERTY_INVOICETAX = "invoiceTax";

    /**
     * Property documentNo stored in column DocumentNo in table C_TaxRegisterline<br>
     * Help: {@literal The document number is usually automatically generated by the system and determined by the
     *       document type of the document. If the document is not saved, the preliminary number is displayed in
     *       "<>". If the document type of your document has no automatic document sequence defined, the field
     *       will be empty when creating a new document. This is for documents which usually have an external
     *       number (like vendor invoice).  If you leave the field empty, the system will generate a document
     *       number for you. The document sequence used for this fallback number is defined in the "Document
     *       Sequence" window with the name "DocumentNo_<TableName>", where TableName is the actual name of the
     *       table inside the database (e.g. C_Order).}
     * 
     */
    public static final String PROPERTY_DOCUMENTNO = "documentNo";

    /**
     * Property tax stored in column C_Tax_ID in table C_TaxRegisterline<br>
     * Help: {@literal The Tax indicates the type of tax for this document line.}
     * 
     */
    public static final String PROPERTY_TAX = "tax";

    /**
     * Property taxableAmount stored in column Taxbaseamt in table C_TaxRegisterline<br>
     * Help: {@literal The Tax Base Amount indicates the base amount used for calculating the tax amount.}
     * 
     */
    public static final String PROPERTY_TAXABLEAMOUNT = "taxableAmount";

    /**
     * Property taxAmount stored in column Taxamt in table C_TaxRegisterline<br>
     * Help: {@literal The Tax Amount displays the total tax amount for a document.}
     * 
     */
    public static final String PROPERTY_TAXAMOUNT = "taxAmount";

    /**
     * Property totalAmount stored in column TotalAmt in table C_TaxRegisterline<br>
     * Help: {@literal The Total Amount indicates the total document amount.}
     * 
     */
    public static final String PROPERTY_TOTALAMOUNT = "totalAmount";

    /**
     * Property undeductableAmount stored in column TaxUndAmt in table C_TaxRegisterline<br>
     * Help: {@literal Tax Undeductable Amount}
     * 
     */
    public static final String PROPERTY_UNDEDUCTABLEAMOUNT = "undeductableAmount";

    /**
     * Property invoiceDate stored in column InvoiceDate in table C_TaxRegisterline
     * 
     */
    public static final String PROPERTY_INVOICEDATE = "invoiceDate";

    /**
     * Property exemptAmount stored in column ExemptAmt in table C_TaxRegisterline<br>
     * Help: {@literal Exempt  amount}
     * 
     */
    public static final String PROPERTY_EXEMPTAMOUNT = "exemptAmount";

    /**
     * Property noVATAmount stored in column Novatamt in table C_TaxRegisterline<br>
     * Help: {@literal No VAT Amount}
     * 
     */
    public static final String PROPERTY_NOVATAMOUNT = "noVATAmount";

    /**
     * Property name stored in column Name in table C_TaxRegisterline 
     * 
     */
    public static final String PROPERTY_NAME = "name";


    public TaxRegisterline() {
        setDefaultValue(PROPERTY_ACTIVE, true);
        setDefaultValue(PROPERTY_CREATIONDATE, new Date());
        setDefaultValue(PROPERTY_UPDATED, new Date());
    }

    @Override
    public String getEntityName() {
        return ENTITY_NAME;
    }

    /**
     * @see TaxRegisterline#PROPERTY_CLIENT
     * 
     */
    public Client getClient() {
        return (Client) get(PROPERTY_CLIENT);
    }
    /**
     * @see TaxRegisterline#PROPERTY_CLIENT
     * 
     */
    public void setClient(Client client) {
        set(PROPERTY_CLIENT, client);
    }

    /**
     * @see TaxRegisterline#PROPERTY_ORGANIZATION
     * 
     */
    public Organization getOrganization() {
        return (Organization) get(PROPERTY_ORGANIZATION);
    }
    /**
     * @see TaxRegisterline#PROPERTY_ORGANIZATION
     * 
     */
    public void setOrganization(Organization organization) {
        set(PROPERTY_ORGANIZATION, organization);
    }

    /**
     * @see TaxRegisterline#PROPERTY_ACTIVE
     * 
     */
    public Boolean isActive() {
        return (Boolean) get(PROPERTY_ACTIVE);
    }
    /**
     * @see TaxRegisterline#PROPERTY_ACTIVE
     * 
     */
    public void setActive(Boolean active) {
        set(PROPERTY_ACTIVE, active);
    }

    /**
     * @see TaxRegisterline#PROPERTY_CREATIONDATE
     * 
     */
    public Date getCreationDate() {
        return (Date) get(PROPERTY_CREATIONDATE);
    }
    /**
     * @see TaxRegisterline#PROPERTY_CREATIONDATE
     * 
     */
    public void setCreationDate(Date creationDate) {
        set(PROPERTY_CREATIONDATE, creationDate);
    }

    /**
     * @see TaxRegisterline#PROPERTY_CREATEDBY
     * 
     */
    public User getCreatedBy() {
        return (User) get(PROPERTY_CREATEDBY);
    }
    /**
     * @see TaxRegisterline#PROPERTY_CREATEDBY
     * 
     */
    public void setCreatedBy(User createdBy) {
        set(PROPERTY_CREATEDBY, createdBy);
    }

    /**
     * @see TaxRegisterline#PROPERTY_UPDATED
     * 
     */
    public Date getUpdated() {
        return (Date) get(PROPERTY_UPDATED);
    }
    /**
     * @see TaxRegisterline#PROPERTY_UPDATED
     * 
     */
    public void setUpdated(Date updated) {
        set(PROPERTY_UPDATED, updated);
    }

    /**
     * @see TaxRegisterline#PROPERTY_UPDATEDBY
     * 
     */
    public User getUpdatedBy() {
        return (User) get(PROPERTY_UPDATEDBY);
    }
    /**
     * @see TaxRegisterline#PROPERTY_UPDATEDBY
     * 
     */
    public void setUpdatedBy(User updatedBy) {
        set(PROPERTY_UPDATEDBY, updatedBy);
    }

    /**
     * @see TaxRegisterline#PROPERTY_ID
     * 
     */
    public String getId() {
        return (String) get(PROPERTY_ID);
    }
    /**
     * @see TaxRegisterline#PROPERTY_ID
     * 
     */
    public void setId(String id) {
        set(PROPERTY_ID, id);
    }

    /**
     * @see TaxRegisterline#PROPERTY_TAXREGISTER
     * 
     */
    public TaxRegister getTaxRegister() {
        return (TaxRegister) get(PROPERTY_TAXREGISTER);
    }
    /**
     * @see TaxRegisterline#PROPERTY_TAXREGISTER
     * 
     */
    public void setTaxRegister(TaxRegister taxRegister) {
        set(PROPERTY_TAXREGISTER, taxRegister);
    }

    /**
     * @see TaxRegisterline#PROPERTY_INVOICETAX
     * 
     */
    public InvoiceTax getInvoiceTax() {
        return (InvoiceTax) get(PROPERTY_INVOICETAX);
    }
    /**
     * @see TaxRegisterline#PROPERTY_INVOICETAX
     * 
     */
    public void setInvoiceTax(InvoiceTax invoiceTax) {
        set(PROPERTY_INVOICETAX, invoiceTax);
    }

    /**
     * @see TaxRegisterline#PROPERTY_DOCUMENTNO
     * 
     */
    public String getDocumentNo() {
        return (String) get(PROPERTY_DOCUMENTNO);
    }
    /**
     * @see TaxRegisterline#PROPERTY_DOCUMENTNO
     * 
     */
    public void setDocumentNo(String documentNo) {
        set(PROPERTY_DOCUMENTNO, documentNo);
    }

    /**
     * @see TaxRegisterline#PROPERTY_TAX
     * 
     */
    public TaxRate getTax() {
        return (TaxRate) get(PROPERTY_TAX);
    }
    /**
     * @see TaxRegisterline#PROPERTY_TAX
     * 
     */
    public void setTax(TaxRate tax) {
        set(PROPERTY_TAX, tax);
    }

    /**
     * @see TaxRegisterline#PROPERTY_TAXABLEAMOUNT
     * 
     */
    public BigDecimal getTaxableAmount() {
        return (BigDecimal) get(PROPERTY_TAXABLEAMOUNT);
    }
    /**
     * @see TaxRegisterline#PROPERTY_TAXABLEAMOUNT
     * 
     */
    public void setTaxableAmount(BigDecimal taxableAmount) {
        set(PROPERTY_TAXABLEAMOUNT, taxableAmount);
    }

    /**
     * @see TaxRegisterline#PROPERTY_TAXAMOUNT
     * 
     */
    public BigDecimal getTaxAmount() {
        return (BigDecimal) get(PROPERTY_TAXAMOUNT);
    }
    /**
     * @see TaxRegisterline#PROPERTY_TAXAMOUNT
     * 
     */
    public void setTaxAmount(BigDecimal taxAmount) {
        set(PROPERTY_TAXAMOUNT, taxAmount);
    }

    /**
     * @see TaxRegisterline#PROPERTY_TOTALAMOUNT
     * 
     */
    public BigDecimal getTotalAmount() {
        return (BigDecimal) get(PROPERTY_TOTALAMOUNT);
    }
    /**
     * @see TaxRegisterline#PROPERTY_TOTALAMOUNT
     * 
     */
    public void setTotalAmount(BigDecimal totalAmount) {
        set(PROPERTY_TOTALAMOUNT, totalAmount);
    }

    /**
     * @see TaxRegisterline#PROPERTY_UNDEDUCTABLEAMOUNT
     * 
     */
    public BigDecimal getUndeductableAmount() {
        return (BigDecimal) get(PROPERTY_UNDEDUCTABLEAMOUNT);
    }
    /**
     * @see TaxRegisterline#PROPERTY_UNDEDUCTABLEAMOUNT
     * 
     */
    public void setUndeductableAmount(BigDecimal undeductableAmount) {
        set(PROPERTY_UNDEDUCTABLEAMOUNT, undeductableAmount);
    }

    /**
     * @see TaxRegisterline#PROPERTY_INVOICEDATE
     * 
     */
    public Date getInvoiceDate() {
        return (Date) get(PROPERTY_INVOICEDATE);
    }
    /**
     * @see TaxRegisterline#PROPERTY_INVOICEDATE
     * 
     */
    public void setInvoiceDate(Date invoiceDate) {
        set(PROPERTY_INVOICEDATE, invoiceDate);
    }

    /**
     * @see TaxRegisterline#PROPERTY_EXEMPTAMOUNT
     * 
     */
    public BigDecimal getExemptAmount() {
        return (BigDecimal) get(PROPERTY_EXEMPTAMOUNT);
    }
    /**
     * @see TaxRegisterline#PROPERTY_EXEMPTAMOUNT
     * 
     */
    public void setExemptAmount(BigDecimal exemptAmount) {
        set(PROPERTY_EXEMPTAMOUNT, exemptAmount);
    }

    /**
     * @see TaxRegisterline#PROPERTY_NOVATAMOUNT
     * 
     */
    public BigDecimal getNoVATAmount() {
        return (BigDecimal) get(PROPERTY_NOVATAMOUNT);
    }
    /**
     * @see TaxRegisterline#PROPERTY_NOVATAMOUNT
     * 
     */
    public void setNoVATAmount(BigDecimal noVATAmount) {
        set(PROPERTY_NOVATAMOUNT, noVATAmount);
    }

    /**
     * @see TaxRegisterline#PROPERTY_NAME
     * 
     */
    public String getName() {
        return (String) get(PROPERTY_NAME);
    }
    /**
     * @see TaxRegisterline#PROPERTY_NAME
     * 
     */
    public void setName(String name) {
        set(PROPERTY_NAME, name);
    }

}
