
/*
 *************************************************************************
 * The contents of this file are subject to the Openbravo  Public  License
 * Version  1.1  (the  "License"),  being   the  Mozilla   Public  License
 * Version 1.1  with a permitted attribution clause; you may not  use this
 * file except in compliance with the License. You  may  obtain  a copy of
 * the License at http://www.openbravo.com/legal/license.html
 * Software distributed under the License  is  distributed  on  an "AS IS"
 * basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
 * License for the specific  language  governing  rights  and  limitations
 * under the License.
 * The Original Code is Openbravo ERP.
 * The Initial Developer of the Original Code is Openbravo SLU
 * All portions are Copyright (C) 2008-2020 Openbravo SLU
 * All Rights Reserved.
 * Contributor(s):  ______________________________________.
 ************************************************************************
*/
package org.openbravo.model.materialmgmt.onhandquantity;

import java.math.BigDecimal;
import java.util.Date;

import org.openbravo.base.structure.ActiveEnabled;
import org.openbravo.base.structure.BaseOBObject;
import org.openbravo.base.structure.ClientEnabled;
import org.openbravo.base.structure.OrganizationEnabled;
import org.openbravo.base.structure.Traceable;
import org.openbravo.model.ad.access.User;
import org.openbravo.model.ad.system.Client;
import org.openbravo.model.common.businesspartner.BusinessPartner;
import org.openbravo.model.common.enterprise.Organization;
import org.openbravo.model.common.order.OrderLine;
/**
 * Entity class for entity PrereservationManualPickEdit (stored in table M_Prereservation_Pick_Edit).
 * <br>
 * NOTE: This class should not be instantiated directly. To instantiate this
 * class the {@link org.openbravo.base.provider.OBProvider} should be used.
 */
public class PrereservationManualPickEdit extends BaseOBObject implements Traceable, ClientEnabled, OrganizationEnabled, ActiveEnabled {
    private static final long serialVersionUID = 1L;
    public static final String TABLE_NAME = "M_Prereservation_Pick_Edit";
    public static final String ENTITY_NAME = "PrereservationManualPickEdit";

    /**
     * Property id stored in column M_Prereservation_Pick_Edit_ID in table M_Prereservation_Pick_Edit 
     * 
     */
    public static final String PROPERTY_ID = "id";

    /**
     * Property client stored in column AD_Client_ID in table M_Prereservation_Pick_Edit 
     * @see ClientEnabled 
     * 
     */
    public static final String PROPERTY_CLIENT = "client";

    /**
     * Property organization stored in column AD_Org_ID in table M_Prereservation_Pick_Edit 
     * @see OrganizationEnabled 
     * 
     */
    public static final String PROPERTY_ORGANIZATION = "organization";

    /**
     * Property createdBy stored in column Createdby in table M_Prereservation_Pick_Edit 
     * @see Traceable 
     * 
     */
    public static final String PROPERTY_CREATEDBY = "createdBy";

    /**
     * Property creationDate stored in column Created in table M_Prereservation_Pick_Edit 
     * @see Traceable 
     * 
     */
    public static final String PROPERTY_CREATIONDATE = "creationDate";

    /**
     * Property updated stored in column Updated in table M_Prereservation_Pick_Edit 
     * @see Traceable 
     * 
     */
    public static final String PROPERTY_UPDATED = "updated";

    /**
     * Property updatedBy stored in column Updatedby in table M_Prereservation_Pick_Edit 
     * @see Traceable 
     * 
     */
    public static final String PROPERTY_UPDATEDBY = "updatedBy";

    /**
     * Property active stored in column Isactive in table M_Prereservation_Pick_Edit 
     * @see ActiveEnabled 
     * 
     */
    public static final String PROPERTY_ACTIVE = "active";

    /**
     * Property purchaseOrderLine stored in column Purchase_Orderline_ID in table M_Prereservation_Pick_Edit<br>
     * Help: {@literal Identifies a Purchase Order Line}
     * 
     */
    public static final String PROPERTY_PURCHASEORDERLINE = "purchaseOrderLine";

    /**
     * Property salesOrderLine stored in column Sales_Orderline_ID in table M_Prereservation_Pick_Edit
     * 
     */
    public static final String PROPERTY_SALESORDERLINE = "salesOrderLine";

    /**
     * Property documentNo stored in column Documentno in table M_Prereservation_Pick_Edit<br>
     * Help: {@literal The document number is usually automatically generated by the system and determined by the
     *       document type of the document. If the document is not saved, the preliminary number is displayed in
     *       "<>". If the document type of your document has no automatic document sequence defined, the field
     *       will be empty when creating a new document. This is for documents which usually have an external
     *       number (like vendor invoice).  If you leave the field empty, the system will generate a document
     *       number for you. The document sequence used for this fallback number is defined in the "Document
     *       Sequence" window with the name "DocumentNo_<TableName>", where TableName is the actual name of the
     *       table inside the database (e.g. C_Order).}
     * 
     */
    public static final String PROPERTY_DOCUMENTNO = "documentNo";

    /**
     * Property lineNo stored in column Line in table M_Prereservation_Pick_Edit<br>
     * Help: {@literal Indicates the unique line for a document.  It will also control the display order of the
     *       lines within a document.}
     * 
     */
    public static final String PROPERTY_LINENO = "lineNo";

    /**
     * Property orderDate stored in column Dateordered in table M_Prereservation_Pick_Edit<br>
     * Help: {@literal Indicates the Date an item was ordered.}
     * 
     */
    public static final String PROPERTY_ORDERDATE = "orderDate";

    /**
     * Property scheduledDeliveryDate stored in column Datepromised in table M_Prereservation_Pick_Edit<br>
     * Help: {@literal Scheduled Delivery Date indicates the date, if any, that an order was promised by.}
     * 
     */
    public static final String PROPERTY_SCHEDULEDDELIVERYDATE = "scheduledDeliveryDate";

    /**
     * Property purchasedQty stored in column Purchasedqty in table M_Prereservation_Pick_Edit
     * 
     */
    public static final String PROPERTY_PURCHASEDQTY = "purchasedQty";

    /**
     * Property receivedQty stored in column Receivedqty in table M_Prereservation_Pick_Edit<br>
     * Help: {@literal Received quantity}
     * 
     */
    public static final String PROPERTY_RECEIVEDQTY = "receivedQty";

    /**
     * Property reservedQty stored in column Reservedqty in table M_Prereservation_Pick_Edit<br>
     * Help: {@literal Represents the total quantity reserved to fulfill the reservation. It cannot be higher
     *       than the pending quantity.}
     * 
     */
    public static final String PROPERTY_RESERVEDQTY = "reservedQty";

    /**
     * Property reservationStock stored in column M_Reservation_Stock_ID in table M_Prereservation_Pick_Edit<br>
     * Help: {@literal The Reservation Stock is each existing stock or purchased stock to fulfill the
     *       Reservation.}
     * 
     */
    public static final String PROPERTY_RESERVATIONSTOCK = "reservationStock";

    /**
     * Property obSelected stored in column OB_Selected in table M_Prereservation_Pick_Edit
     * 
     */
    public static final String PROPERTY_OBSELECTED = "obSelected";

    /**
     * Property orderedQuantity stored in column Qtyordered in table M_Prereservation_Pick_Edit<br>
     * Help: {@literal The Ordered Quantity indicates the quantity of a product that was ordered.}
     * 
     */
    public static final String PROPERTY_ORDEREDQUANTITY = "orderedQuantity";

    /**
     * Property deliveredQuantity stored in column Qtydelivered in table M_Prereservation_Pick_Edit<br>
     * Help: {@literal The Delivered Quantity indicates the quantity of a product that has already been
     *       delivered.}
     * 
     */
    public static final String PROPERTY_DELIVEREDQUANTITY = "deliveredQuantity";

    /**
     * Property stockReservation stored in column M_Reservation_ID in table M_Prereservation_Pick_Edit<br>
     * Help: {@literal The Reservation is the definition of a product reservation is set the owner, the quantity
     *       and the desired dimensions.}
     * 
     */
    public static final String PROPERTY_STOCKRESERVATION = "stockReservation";

    /**
     * Property otherReservedQty stored in column Otherresqty in table M_Prereservation_Pick_Edit
     * 
     */
    public static final String PROPERTY_OTHERRESERVEDQTY = "otherReservedQty";

    /**
     * Property businessPartner stored in column C_Bpartner_ID in table M_Prereservation_Pick_Edit<br>
     * Help: {@literal A Business Partner is anyone with whom you transact.  This can include a customer, vendor,
     *       employee or any combination of these.}
     * 
     */
    public static final String PROPERTY_BUSINESSPARTNER = "businessPartner";

    /**
     * Property allocated stored in column Isallocated in table M_Prereservation_Pick_Edit<br>
     * Help: {@literal An Allocated Reservation Stock means that the referenced stock and quantity can only be
     *       used to fulfill this Reservation.}
     * 
     */
    public static final String PROPERTY_ALLOCATED = "allocated";


    public PrereservationManualPickEdit() {
        setDefaultValue(PROPERTY_ACTIVE, true);
        setDefaultValue(PROPERTY_OBSELECTED, false);
        setDefaultValue(PROPERTY_ALLOCATED, false);
    }

    @Override
    public String getEntityName() {
        return ENTITY_NAME;
    }

    /**
     * @see PrereservationManualPickEdit#PROPERTY_ID
     * 
     */
    public String getId() {
        return (String) get(PROPERTY_ID);
    }
    /**
     * @see PrereservationManualPickEdit#PROPERTY_ID
     * 
     */
    public void setId(String id) {
        set(PROPERTY_ID, id);
    }

    /**
     * @see PrereservationManualPickEdit#PROPERTY_CLIENT
     * 
     */
    public Client getClient() {
        return (Client) get(PROPERTY_CLIENT);
    }
    /**
     * @see PrereservationManualPickEdit#PROPERTY_CLIENT
     * 
     */
    public void setClient(Client client) {
        set(PROPERTY_CLIENT, client);
    }

    /**
     * @see PrereservationManualPickEdit#PROPERTY_ORGANIZATION
     * 
     */
    public Organization getOrganization() {
        return (Organization) get(PROPERTY_ORGANIZATION);
    }
    /**
     * @see PrereservationManualPickEdit#PROPERTY_ORGANIZATION
     * 
     */
    public void setOrganization(Organization organization) {
        set(PROPERTY_ORGANIZATION, organization);
    }

    /**
     * @see PrereservationManualPickEdit#PROPERTY_CREATEDBY
     * 
     */
    public User getCreatedBy() {
        return (User) get(PROPERTY_CREATEDBY);
    }
    /**
     * @see PrereservationManualPickEdit#PROPERTY_CREATEDBY
     * 
     */
    public void setCreatedBy(User createdBy) {
        set(PROPERTY_CREATEDBY, createdBy);
    }

    /**
     * @see PrereservationManualPickEdit#PROPERTY_CREATIONDATE
     * 
     */
    public Date getCreationDate() {
        return (Date) get(PROPERTY_CREATIONDATE);
    }
    /**
     * @see PrereservationManualPickEdit#PROPERTY_CREATIONDATE
     * 
     */
    public void setCreationDate(Date creationDate) {
        set(PROPERTY_CREATIONDATE, creationDate);
    }

    /**
     * @see PrereservationManualPickEdit#PROPERTY_UPDATED
     * 
     */
    public Date getUpdated() {
        return (Date) get(PROPERTY_UPDATED);
    }
    /**
     * @see PrereservationManualPickEdit#PROPERTY_UPDATED
     * 
     */
    public void setUpdated(Date updated) {
        set(PROPERTY_UPDATED, updated);
    }

    /**
     * @see PrereservationManualPickEdit#PROPERTY_UPDATEDBY
     * 
     */
    public User getUpdatedBy() {
        return (User) get(PROPERTY_UPDATEDBY);
    }
    /**
     * @see PrereservationManualPickEdit#PROPERTY_UPDATEDBY
     * 
     */
    public void setUpdatedBy(User updatedBy) {
        set(PROPERTY_UPDATEDBY, updatedBy);
    }

    /**
     * @see PrereservationManualPickEdit#PROPERTY_ACTIVE
     * 
     */
    public Boolean isActive() {
        return (Boolean) get(PROPERTY_ACTIVE);
    }
    /**
     * @see PrereservationManualPickEdit#PROPERTY_ACTIVE
     * 
     */
    public void setActive(Boolean active) {
        set(PROPERTY_ACTIVE, active);
    }

    /**
     * @see PrereservationManualPickEdit#PROPERTY_PURCHASEORDERLINE
     * 
     */
    public OrderLine getPurchaseOrderLine() {
        return (OrderLine) get(PROPERTY_PURCHASEORDERLINE);
    }
    /**
     * @see PrereservationManualPickEdit#PROPERTY_PURCHASEORDERLINE
     * 
     */
    public void setPurchaseOrderLine(OrderLine purchaseOrderLine) {
        set(PROPERTY_PURCHASEORDERLINE, purchaseOrderLine);
    }

    /**
     * @see PrereservationManualPickEdit#PROPERTY_SALESORDERLINE
     * 
     */
    public OrderLine getSalesOrderLine() {
        return (OrderLine) get(PROPERTY_SALESORDERLINE);
    }
    /**
     * @see PrereservationManualPickEdit#PROPERTY_SALESORDERLINE
     * 
     */
    public void setSalesOrderLine(OrderLine salesOrderLine) {
        set(PROPERTY_SALESORDERLINE, salesOrderLine);
    }

    /**
     * @see PrereservationManualPickEdit#PROPERTY_DOCUMENTNO
     * 
     */
    public String getDocumentNo() {
        return (String) get(PROPERTY_DOCUMENTNO);
    }
    /**
     * @see PrereservationManualPickEdit#PROPERTY_DOCUMENTNO
     * 
     */
    public void setDocumentNo(String documentNo) {
        set(PROPERTY_DOCUMENTNO, documentNo);
    }

    /**
     * @see PrereservationManualPickEdit#PROPERTY_LINENO
     * 
     */
    public Long getLineNo() {
        return (Long) get(PROPERTY_LINENO);
    }
    /**
     * @see PrereservationManualPickEdit#PROPERTY_LINENO
     * 
     */
    public void setLineNo(Long lineNo) {
        set(PROPERTY_LINENO, lineNo);
    }

    /**
     * @see PrereservationManualPickEdit#PROPERTY_ORDERDATE
     * 
     */
    public Date getOrderDate() {
        return (Date) get(PROPERTY_ORDERDATE);
    }
    /**
     * @see PrereservationManualPickEdit#PROPERTY_ORDERDATE
     * 
     */
    public void setOrderDate(Date orderDate) {
        set(PROPERTY_ORDERDATE, orderDate);
    }

    /**
     * @see PrereservationManualPickEdit#PROPERTY_SCHEDULEDDELIVERYDATE
     * 
     */
    public Date getScheduledDeliveryDate() {
        return (Date) get(PROPERTY_SCHEDULEDDELIVERYDATE);
    }
    /**
     * @see PrereservationManualPickEdit#PROPERTY_SCHEDULEDDELIVERYDATE
     * 
     */
    public void setScheduledDeliveryDate(Date scheduledDeliveryDate) {
        set(PROPERTY_SCHEDULEDDELIVERYDATE, scheduledDeliveryDate);
    }

    /**
     * @see PrereservationManualPickEdit#PROPERTY_PURCHASEDQTY
     * 
     */
    public BigDecimal getPurchasedQty() {
        return (BigDecimal) get(PROPERTY_PURCHASEDQTY);
    }
    /**
     * @see PrereservationManualPickEdit#PROPERTY_PURCHASEDQTY
     * 
     */
    public void setPurchasedQty(BigDecimal purchasedQty) {
        set(PROPERTY_PURCHASEDQTY, purchasedQty);
    }

    /**
     * @see PrereservationManualPickEdit#PROPERTY_RECEIVEDQTY
     * 
     */
    public BigDecimal getReceivedQty() {
        return (BigDecimal) get(PROPERTY_RECEIVEDQTY);
    }
    /**
     * @see PrereservationManualPickEdit#PROPERTY_RECEIVEDQTY
     * 
     */
    public void setReceivedQty(BigDecimal receivedQty) {
        set(PROPERTY_RECEIVEDQTY, receivedQty);
    }

    /**
     * @see PrereservationManualPickEdit#PROPERTY_RESERVEDQTY
     * 
     */
    public BigDecimal getReservedQty() {
        return (BigDecimal) get(PROPERTY_RESERVEDQTY);
    }
    /**
     * @see PrereservationManualPickEdit#PROPERTY_RESERVEDQTY
     * 
     */
    public void setReservedQty(BigDecimal reservedQty) {
        set(PROPERTY_RESERVEDQTY, reservedQty);
    }

    /**
     * @see PrereservationManualPickEdit#PROPERTY_RESERVATIONSTOCK
     * 
     */
    public ReservationStock getReservationStock() {
        return (ReservationStock) get(PROPERTY_RESERVATIONSTOCK);
    }
    /**
     * @see PrereservationManualPickEdit#PROPERTY_RESERVATIONSTOCK
     * 
     */
    public void setReservationStock(ReservationStock reservationStock) {
        set(PROPERTY_RESERVATIONSTOCK, reservationStock);
    }

    /**
     * @see PrereservationManualPickEdit#PROPERTY_OBSELECTED
     * 
     */
    public Boolean isObSelected() {
        return (Boolean) get(PROPERTY_OBSELECTED);
    }
    /**
     * @see PrereservationManualPickEdit#PROPERTY_OBSELECTED
     * 
     */
    public void setObSelected(Boolean obSelected) {
        set(PROPERTY_OBSELECTED, obSelected);
    }

    /**
     * @see PrereservationManualPickEdit#PROPERTY_ORDEREDQUANTITY
     * 
     */
    public BigDecimal getOrderedQuantity() {
        return (BigDecimal) get(PROPERTY_ORDEREDQUANTITY);
    }
    /**
     * @see PrereservationManualPickEdit#PROPERTY_ORDEREDQUANTITY
     * 
     */
    public void setOrderedQuantity(BigDecimal orderedQuantity) {
        set(PROPERTY_ORDEREDQUANTITY, orderedQuantity);
    }

    /**
     * @see PrereservationManualPickEdit#PROPERTY_DELIVEREDQUANTITY
     * 
     */
    public BigDecimal getDeliveredQuantity() {
        return (BigDecimal) get(PROPERTY_DELIVEREDQUANTITY);
    }
    /**
     * @see PrereservationManualPickEdit#PROPERTY_DELIVEREDQUANTITY
     * 
     */
    public void setDeliveredQuantity(BigDecimal deliveredQuantity) {
        set(PROPERTY_DELIVEREDQUANTITY, deliveredQuantity);
    }

    /**
     * @see PrereservationManualPickEdit#PROPERTY_STOCKRESERVATION
     * 
     */
    public Reservation getStockReservation() {
        return (Reservation) get(PROPERTY_STOCKRESERVATION);
    }
    /**
     * @see PrereservationManualPickEdit#PROPERTY_STOCKRESERVATION
     * 
     */
    public void setStockReservation(Reservation stockReservation) {
        set(PROPERTY_STOCKRESERVATION, stockReservation);
    }

    /**
     * @see PrereservationManualPickEdit#PROPERTY_OTHERRESERVEDQTY
     * 
     */
    public BigDecimal getOtherReservedQty() {
        return (BigDecimal) get(PROPERTY_OTHERRESERVEDQTY);
    }
    /**
     * @see PrereservationManualPickEdit#PROPERTY_OTHERRESERVEDQTY
     * 
     */
    public void setOtherReservedQty(BigDecimal otherReservedQty) {
        set(PROPERTY_OTHERRESERVEDQTY, otherReservedQty);
    }

    /**
     * @see PrereservationManualPickEdit#PROPERTY_BUSINESSPARTNER
     * 
     */
    public BusinessPartner getBusinessPartner() {
        return (BusinessPartner) get(PROPERTY_BUSINESSPARTNER);
    }
    /**
     * @see PrereservationManualPickEdit#PROPERTY_BUSINESSPARTNER
     * 
     */
    public void setBusinessPartner(BusinessPartner businessPartner) {
        set(PROPERTY_BUSINESSPARTNER, businessPartner);
    }

    /**
     * @see PrereservationManualPickEdit#PROPERTY_ALLOCATED
     * 
     */
    public Boolean isAllocated() {
        return (Boolean) get(PROPERTY_ALLOCATED);
    }
    /**
     * @see PrereservationManualPickEdit#PROPERTY_ALLOCATED
     * 
     */
    public void setAllocated(Boolean allocated) {
        set(PROPERTY_ALLOCATED, allocated);
    }

}
